### ISSUE TITLE
generate: mismatch type assignment for `cm.Reinterpret`

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wasm-tools-go#165]
## Issue

Consider the following WIT
```wit
package my:resources;

interface types {
  resource z {
    constructor(a: f64);
  }
}

world resources {
  use types.{z};

  record big {
    x1: borrow<z>,
  }

  export big-record: func(r: big);
}
```

The generated Go code is the following:
```go
//abi.go
package resources

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
)

func lift_Big(f0 uint32) (v Big) {
	v.X1 = cm.Reinterpret[cm.Rep](f0)
	return
}
```

While `cm.Rep` and the type of `v.X1` which is `cm.Resource` are both based on `uint32`, but due to the two declaration, Go compiler treats them differently, and hence it produces the following error message:

```
cannot use cm.Reinterpret[cm.Rep](f0) (value of type cm.Rep) as types.Z value in assignment
```

**Comment by ydnar** [comment]
Aha, found another missing cast!

**Comment by Mossaka** [comment]
I am not exactly sure how to fix this issue, as I tried to add a `cast ` call to [this line](https://github.com/Mossaka/wasm-tools-go-fork/blob/main/wit/bindgen/generator.go#L1260) but other resource tests fail afterwards. I think this is due to the asymmetry design of the `func (g *generator) borrowRep()` function where "Exported borrow<T> are represented by a concrete i32 rep".

Perhaps, the fix needs to do a special casing for "exported borrow" type in lifting and cast it back to the Resource type defined from generated code. @ydnar

**Comment by ydnar** [comment]
Taking a look…

**Comment by ydnar** [comment]
I think the problem is that it's trying to lift an imported type. It can't discriminate between the two at this point. 

Maybe we can add a kludge to figure out which type (imported vs exported) to use?

Wondering if it's time to split the types in wasm-tools.

**Comment by Mossaka** [comment]
what walkaround are you thinking about?
