### ISSUE TITLE
wit: logical flaw in `TestHasBorrow` function

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wasm-tools-go#167]
Consider the following WIT:

```wit
package foo:bar;

world x {
  resource y;

  record r {
    y: borrow<y>
  }

  import f: func(a: list<r>);
}
```

The `TestHasBorrow` function returns an error for this case saying `testdata_test.go:493: has "borrow<": false != HasBorrow(td): true (list<r>)`

But `list<r>` does contain a `borrow` type, in record `r`'s field. I believe that simplify by asserting if the type WIT has `borrow<` syntax is not enough due to the existance of the anonymous types (e.g. `list`, `result`, `option`, etc.) in WIT.

## Discussion

For anonymous types like `list`, we will need to recursively go into the nested type to check if borrow type exists, this might be a bit hard to do as a unit test case, because you might need to re-implement the recursive logic for that. I am thinking about skipping the anonymous type for this case and adding specific, predefined test cases with known expected results.

**Comment by ydnar** [comment]
Proposed fix makes sense. Thanks @mossaka!
