### ISSUE TITLE
wit/bindgen: mangled symbol generation for inline functions and interfaces in worlds is wrong

### ISSUE THREAD

**Issue by ydnar** [bytecodealliance/wasm-tools-go#175]
For the given WIT:

```wit
package issues:issue175;

world w {
	export example: interface {
		f1: func() -> s32;
		resource r {
			constructor(a: f64);
			get-a: func() -> f64;
			set-a: func(a: f64);
			add: static func(r: r, a: f64) -> r;
		}
	}
	export f2: func() -> s64;
}
```

- `wit-bindgen-go` generates `//go:wasmexport issues:issue170/w#f`
- `wit-bindgen` generates `__attribute__((__export_name__("f")))`

Implication: inline interfaces and functions imported into or exported from a world, are not package-qualified. `wit-bindgen-go` should be updated to reflect this.

**Comment by deadprogram** [comment]
@ydnar one question about this change: is there a way to still get the same output as far as code generation is concerned?

My previous function signatures/generated packages that were `wasm:cv/cv#do-something` are now `$root#do-something`

I tried to switch to using an extra interface , but that caused me to get a message `duplicate item named `cv`.

What do you think?

**Comment by ydnar** [comment]
What are your source WIT files? I think we can adapt them to get the result you're looking for.

**Comment by deadprogram** [comment]
Please see https://github.com/wasmvision/wasmcv/pull/3
