### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by MendyBerger** [bytecodealliance/wasm-tools-go#197]
How do I install this package? I don't see any instructions on installation.

I'm new to Go, so sorry if this is obvious to Go devs.

**Comment by ydnar** [comment]
Hi there. We can add some initial setup and install instructions to the README.

This project is targeted primarily at package authors building Go bindings for WIT interfaces. Think the "syscall" layer.

Package `cm` provides runtime support for Go interfaces generated by package `wit/bindgen`. The typical use case is via the `wit-bindgen-go` CLI tool.

**Comment by MendyBerger** [comment]
:facepalm: I was conflating `wasm-tools-go` with `wit-bindgen-go`.

Thanks for the clarification, I'll close this now.
