### ISSUE TITLE
type alias declared in .wit file does not generate a named type

### ISSUE THREAD

**Issue by deadprogram** [bytecodealliance/wasm-tools-go#204]
I added a type alias to one of my wit files like this:

```
    /// size is a 2-element integer vector.
    /// It represents a width and height.
    record size {
        x: s32,
        y: s32,
    }

    /// point is a 2-element integer vector.
    /// It represents a x and y coordinate.
    type point = size;
```

The generated code substituted `Size` everywhere that the wit file used `point` which was not incorrect as far as typing/compilation, but did not achieve my objective of code readability which is why I created the alias.

What I expected was some Go code like this:

```go
type Point Size
```

`wit-bindgen` for Rust did add named alias to generated code:

```rust
      /// point is a 2-element integer vector.
      /// It represents a x and y coordinate.
      pub type Point = Size;
```

Likewise C

```c
// point is a 2-element integer vector.
// It represents a x and y coordinate.
typedef wasm_cv_types_size_t wasm_cv_types_point_t;
```

**Comment by ydnar** [comment]
Interesting!

The generator does support aliases, but that code path is disabled by default due to how it's used pervasively in the default worlds.

I hadn't seen same-package aliases used in this way before. Happy to take a look.
