### ISSUE TITLE
Ability to control log output in wit-bindgen-go

### ISSUE THREAD

**Issue by vados-cosmonic** [bytecodealliance/wasm-tools-go#212]
Hey all, when running `wit-bindgen-go` I'd like the ability to be able to silence/control the output.

I'm particularly thinking about the use case of a dev tool whose output looks something like this:

```
starting build...
<build output, which happens to include wasm-tools-go output>
build complete
[hint] access your X at Y!
```
At present, the build output gets quite lengthy and would grow with the complexity of the project/amount of work `wasm-tools-go` is doing.

It's possible to implement suppression of output at the (higher) dev tool level, but it might be a bit more convenient if `wit-bindgen-go` could control logging levels and/or silence by default and let people opt in to more verbose output?

I asked around and it seems like the place to land changes would be [in `wit-bindgen-go`](https://github.com/bytecodealliance/wasm-tools-go/blob/c7ba7685c93df814db29bd500839dba85bca56e2/cmd/wit-bindgen-go/cmd/generate/generate.go#L146) -- does that sound reasonable?

**Comment by Mossaka** [comment]
I think it totally makes sense to me to add a logging control to the `wit-bindgen-go` cmd. We may use the [`log` package](https://pkg.go.dev/log) from Go standard library. Are you interested in implementing it? 

CC @ydnar

**Comment by vados-cosmonic** [comment]
Yeah I'd be happy to work on it! Would love to hear of the idiomatic way to do it though, given the current codebase/organization -- I haven't written a large amount of Go for a while!

**Comment by ydnar** [comment]
I think it's reasonable to move some of the output behind a -v flag.
